import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';  // Correct import
import {Outfit} from 'next/font/google';

export const metadata = {
  title: 'Vionyx',
  description: 'Generated by create next app'
};
const outfit = Outfit({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={outfit.className}>
          {children}  {/* Render children directly */}
        </body>
      </html>
    </ClerkProvider>
  );
}
