import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Outfit } from 'next/font/google';

export const metadata = {
  title: 'Vionyx',
  description: 'Generated by create next app',
};

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit', // optional, if you're using CSS vars
  display: 'swap', // optional, for better UX
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={outfit.className}>
        <body>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
